routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
	return view('auth/login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/mapel', 'MapelController');
    Route::resource('/guru', 'GuruController');
    Route::resource('/fasilitas', 'FasilitasController');
    Route::resource('/tpendidik', 'TpendidikController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/tag', 'TagController');
    Route::resource('/post', 'PostController');
    Route::resource('/visimisi','VisiMisiController');
});

app/Tpendidik.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tpendidik extends Model
{
    protected $table = 'table_tpendidik';
    protected $fillable = ['name', 'foto'];
}

app/Http/Controllers/TpendidikController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tpendidik;

class TpendidikController extends Controller{
    public function index(){
        $tpendidik = Tpendidik::all();
        return view('admin.tpendidik.index', compact('tpendidik'));
    }

    public function create(){
        return view('admin.tpendidik.create');
    }

    public function store(Request $request){
        $this->validate($request, [
            'name' => 'required|min:5|max:30',
            'foto' => 'required',
        ]);

        $foto = $request->foto;
        $new_foto = time() . $foto->getClientOriginalName();

        Tpendidik::create([
            'name' => $request->name,
            'foto' => 'public/uploads/tpendidik/' . $new_foto

        ]);

        $foto->move('public/uploads/tpendidik/', $new_foto);


        return redirect()->route('tpendidik.index')->with('success', 'Data Berhasil Disimpan');
    }

    public function edit($id){
        $tpendidik = Tpendidik::findorfail($id);
        return view('admin.tpendidik.edit', compact('tpendidik'));
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'name' => 'required|min:5|max:30',
            'foto' => 'required'

        ]);

        $tpendidik = Tpendidik::findorfail($id);

        if ($request->has('foto')) {
            $foto = $request->foto;
            $new_foto = time() . $foto->getClientOriginalName();
            $foto->move('public/uploads/tpendidik/', $new_foto);

            $tpendidik_data = [
                'name' => $request->name,
                'foto' => $request->foto,
            ];
        } else {
            $tpendidik_data = [
                'name' => $request->name,
                'foto' => $request->foto,
            ];
        }

        $tpendidik->update($tpendidik_data);
        return redirect()->route('tpendidik.index')->with('success', 'Data Berhasil Disimpan');
    }

    public function destroy($id){
        $tpendidik = Tpendidik::findorfail($id);
        $tpendidik->delete();

        return redirect()->back()->with('success', 'Data Berhasil Dihapus');
    }
}

resources/views/admin/tpendidik/create.blade.php
@extends('backend.index')
@section('sub-judul','Tambah Tenaga Kependidikan')
@section('halaman-sekarang','Tambah Tenaga Kependidikan')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('tpendidik.index') }}" class="btn btn-warning btn-sm">Kembali</a>
        </div>
      </div>
      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-md-6">
            <form class="form-horizontal" method="POST" action="{{ route('tpendidik.store') }}" enctype="multipart/form-data">
              @csrf

              <div class="form-group">
                <label>Nama Tenaga Kependidikan</label>
                <input type="text" class="form-control" name="name" placeholder="Input Nama">
                <div class="text-danger">@error('name') {{ $message }} @enderror</div>
              </div>
              <div class="form-group">
                <label>Foto Guru</label>
                <input type="file" class="form-control" id="thumbnail" name="foto" accept=".jpg, .png, .jpeg">
                <div class="text-danger">@error('foto') {{ $message }} @enderror</div>
              </div>
              <div id="thumbnail-preview"></div>
              <button type="submit" class="btn btn-info">Simpan</button>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){

    $("#thumbnail").on('change', function(){
      thumbnail(this);
    });
  })
  function thumbnail(input) {
    if (input.files && input.files[0]) {
      var thumnail_preview = $('#thumbnail-preview');
      thumnail_preview.empty();
      var reader = new FileReader();

      reader.onload = function(e) {
        $("<img />", {
          "src": e.target.result,
          "class": "preview-img pb-3",
          "width": "300",
          "height": "300"
        }).appendTo(thumnail_preview);
      }
      thumnail_preview.show();
      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

@endsection

resources/views/admin/tpendidik/edit.blade.php
@extends('backend.index')
@section('sub-judul','Edit Tenaga Kependidikan')
@section('halaman-sekarang','Edit Tenaga Kependidikan')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('tpendidik.index') }}" class="btn btn-warning btn-sm">Kembali</a>
        </div>
      </div>
      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-md-6">
            <form class="form-horizontal" method="POST" action="{{ route('tpendidik.update', $tpendidik->id) }}" enctype="multipart/form-data">
              @csrf
              @method('PUT')

              <div class="form-group">
                <label>Nama Tenaga Kependidikan</label>
                <input type="text" class="form-control" name="name" value="{{ $tpendidik->name }}">
                <div class="text-danger">@error('name') {{ $message }} @enderror</div>
              </div>
              <div class="form-group">
                <label>Foto Guru</label>
                <input type="file" class="form-control" id="thumbnail" name="foto" accept=".jpg, .png, .jpeg">
                <div class="text-danger">@error('foto') {{ $message }} @enderror</div>
              </div>
              <div id="thumbnail-preview"></div>
              <button type="submit" class="btn btn-info">Simpan</button>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){

    $("#thumbnail").on('change', function(){
      thumbnail(this);
    });
  })
  function thumbnail(input) {
    if (input.files && input.files[0]) {
      var thumnail_preview = $('#thumbnail-preview');
      thumnail_preview.empty();
      var reader = new FileReader();

      reader.onload = function(e) {
        $("<img />", {
          "src": e.target.result,
          "class": "preview-img pb-3",
          "width": "300",
          "height": "300"
        }).appendTo(thumnail_preview);
      }
      thumnail_preview.show();
      reader.readAsDataURL(input.files[0]);
    }
  }
</script>


@endsection

resources/views/admin/tpendidik/index.blade.php
@extends('backend.index')
@section('sub-judul','Tenaga Pendidik')
@section('halaman-sekarang','Tenaga Kependidikan')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('tpendidik.create') }}" class="btn btn-primary btn-flat btn-sm"><i class="fas fa-plus"></i> Tambah</a>
        </div>
      </div>

      <div class="card-body">
        <table id="example2" class="table table-bordered table-hover">
          <thead>
            <tr>
              <th width="10%">No</th>
              <th>Nama Pengelola tpendidik</th>
              <th>Foto</th>
              <th width="10%">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @foreach( $tpendidik as $result => $hasil)
            <tr>
              <td>{{ $loop->iteration }}</td>
              <td>{{ $hasil->name }}</td>
              <td><img src="{{ asset( $hasil->foto ) }}" class="img-fluid" width="100px" alt=""></td>
              <td>
                <form action="{{ route('tpendidik.destroy', $hasil->id )}}" method="POST">
                  @csrf
                  @method('delete')
                  <a href="{{ route('tpendidik.edit', $hasil->id ) }}" class="btn btn-primary"><i class="fas fa-edit"></i>Edit</a>
                  <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i>Delete</button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

@endsection