routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
	return view('auth/login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/mapel', 'MapelController');
    Route::resource('/guru', 'GuruController');
    Route::resource('/fasilitas', 'FasilitasController');
    Route::resource('/tpendidik', 'TpendidikController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/tag', 'TagController');
    Route::resource('/post', 'PostController');
    Route::resource('/visimisi','VisiMisiController');
});

app/Tags.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tags extends Model
{
    protected $table = 'table_tags';
    protected $fillable = ['name', 'slug'];

    public function post()
    {
        return $this->belongsToMany('App\Posts');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tags;
use Illuminate\Support\Str;

class TagController extends Controller{
    public function index(){
        $tag = Tags::all();
        return view('admin.tag.index', compact('tag'));
    }

    public function create(){
        return view('admin.tag.create');
    }

    public function store(Request $request){
        $this->validate($request, [
            'name' => 'required|min:3|max:30'
        ]);

        Tags::create([
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ]);
        return redirect()->back()->with('success', 'Data Berhasil Disimpan');
    }

    public function edit($id){
        $tag = Tags::findorfail($id);
        return view('admin.tag.edit', compact('tag'));
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'name' => 'required|min:3|max:30'
        ]);


        $tag_data = [
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ];

        Tags::whereId($id)->update($tag_data);

        return redirect()->route('tag.index')->with('success', 'Data Berhasil Disimpan');
    }

    public function destroy($id){
        $tags = Tags::findorfail($id);
        $tags->delete();

        return redirect()->back()->with('success', 'Data Berhasil Dihapus');
    }
}

resources/views/admin/tag/create.blade.php
@extends('backend.index')
@section('sub-judul','Tag')
@section('halaman-sekarang','Tag')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('tag.index') }}" class="btn btn-warning btn-sm">Kembali</a>
        </div>
      </div>
      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-md-6">
            <form class="form-horizontal" method="POST" action="{{ route('tag.store') }}">
              @csrf

              <div class="form-group">
                <label>Nama Tag</label>
                <input type="text" class="form-control" name="name" placeholder="Input Nama">
                <div class="text-danger">@error('name') {{ $message }} @enderror</div>
              </div>
              <button type="submit" class="btn btn-info">Simpan</button>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/tag/edit.blade.php
@extends('backend.index')
@section('sub-judul','Edit Data Mata Pelajaran')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('tag.index') }}" class="btn btn-warning btn-sm">Kembali</a>
        </div>
      </div>
      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-md-6">
            <form class="form-horizontal" method="POST" action="{{ route('tag.update', $tag->id) }}">
              @csrf
              @method('PUT')

              <div class="form-group">
                <label>Nama Tag</label>
                <input type="text" class="form-control" name="name" value="{{ $tag->name }}">
                <div class="text-danger">@error('name') {{ $message }} @enderror</div>
              </div>
              <button type="submit" class="btn btn-info">Simpan</button>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/tag/index.blade.php
@extends('backend.index')
@section('sub-judul','Tag')
@section('halaman-sekarang','Tag')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('tag.create') }}" class="btn btn-primary btn-flat btn-sm"><i class="fas fa-plus"></i> Tambah</a>
        </div>
      </div>

      <div class="card-body">
        <table id="example2" class="table table-bordered table-hover">
          <thead>
            <tr>
              <th width="10%">No</th>
              <th>Nama Tag</th>
              <th width="10%">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @foreach( $tag as $result => $hasil)
            <tr>
              <td>{{ $loop->iteration }}</td>
              <td>{{ $hasil->name}}</td>
              <td>
                <form action="{{ route('tag.destroy', $hasil->id )}}" method="POST">
                  @csrf
                  @method('delete')
                  <a href="{{ route('tag.edit', $hasil->id ) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                  <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


@endsection