routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
	return view('auth/login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/mapel', 'MapelController');
    Route::resource('/guru', 'GuruController');
    Route::resource('/fasilitas', 'FasilitasController');
    Route::resource('/tpendidik', 'TpendidikController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/tag', 'TagController');
    Route::resource('/post', 'PostController');
    Route::resource('/visimisi','VisiMisiController');
});

app/Http/Controllers/VisiMisiController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Visidanmisi;

class VisiMisiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $visimisi = Visidanmisi::all();
        return view('admin.visimisi.index', compact('visimisi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.visimisi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            "visi" => 'required',
            "misi" => 'required'
        ]);

        Visidanmisi::create([
            "visi" => $request->visi,
            "misi" => $request->misi
        ]);

        return redirect()->route('visimisi.index')->with('success', 'Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $visimisi = Visidanmisi::findorfail($id);
        return view('admin.visimisi.edit', compact('visimisi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'visi' => 'required',
            'misi' => 'required'
        ]);

        $visimisi_data = [
            'visi' => $request->visi,
            'misi' => $request->misi
        ];

        Visidanmisi::whereId($id)->update($visimisi_data);
        return redirect()->route('visimisi.index')->with('success', 'Data Berhasil Disimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $visimisi = Visidanmisi::findorfail($id);
        $visimisi->delete();

        return redirect()->back()->with('success', 'Data Berhasil Dihapus');
    }
}

resources/views/admin/visimisi/create.blade.php
@extends('backend.index')
@section('sub-judul','Tambah Mata Pelajaran')
@section('halaman-sekarang','Tambah Mata Pelajaran')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('visimisi.index') }}" class="btn btn-warning btn-sm">Kembali</a>
        </div>
      </div>
      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-md-6">
            <form class="form-horizontal" method="POST" action="{{ route('visimisi.store') }}">
              @csrf

              <div class="form-group">
                <label>Visi</label>
                <textarea class="form-control" name="visi"></textarea>
                <div class="text-danger">@error('visi') {{ $message }} @enderror</div>
              </div>
              <div class="form-group">
                <label>Misi</label>
                <textarea class="form-control" name="misi"></textarea>
                <div class="text-danger">@error('misi') {{ $message }} @enderror</div>
              </div>
              <button type="submit" class="btn btn-info">Simpan</button>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


<script >
    CKEDITOR.replace('visi');
  </script>

<script >
    CKEDITOR.replace('misi');
  </script>

@endsection

resources/views/admin/visimisi/edit.blade.php
@extends('backend.index')
@section('sub-judul','Edit Mata Pelajaran')
@section('halaman-sekarang','Edit Mata Pelajaran')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('visimisi.index') }}" class="btn btn-warning btn-sm">Kembali</a>
        </div>
      </div>
      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-md-6">
            <form class="form-horizontal" method="POST" action="{{ route('visimisi.update', $visimisi->id) }}">
              @csrf
              @method('PUT')

              <div class="form-group">
                <label>Visi</label>
                <textarea class="form-control" name="visi">{{ $visimisi->visi }}</textarea>
                <div class="text-danger">@error('visi') {{ $message }} @enderror</div>
              </div>
              <div class="form-group">
                <label>Misi</label>
                <textarea class="form-control" name="misi">{{ $visimisi->misi }}</textarea>
                <div class="text-danger">@error('misi') {{ $message }} @enderror</div>
              </div>

              <button type="submit" class="btn btn-info">Simpan</button>
            </form>
          </div>
        </div>

      </div>
    </div>

  </div>
</div>


<script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
<script >
  CKEDITOR.replace( 'visi' );
  CKEDITOR.replace( 'misi' );

</script>


@endsection

resources/views/admin/visimisi/index.blade.php
@extends('backend.index')
@section('sub-judul','Visi & Misi')
@section('halaman-sekarang','Visi & Misi')
@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="float-right">
          <a href="{{ route('visimisi.create') }}" class="btn btn-primary btn-flat btn-sm"><i class="fas fa-plus"></i> Tambah</a>
        </div>
      </div>

      <div class="card-body">
        <table id="example2" class="table table-bordered table-hover">
          <thead>
            <tr>
              <th width="10%">No</th>
              <th>Visi</th>
              <th>Misi</th>
              <th width="10%">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @foreach( $visimisi as $result => $hasil)
            <tr>
              <td>{{ $loop->iteration }}</td>
              <td>{{ $hasil->visi }}</td>
              <td>{{ $hasil->misi}}</td>
              <td>
                <form action="{{ route('visimisi.destroy', $hasil->id )}}" method="POST">
                  @csrf
                  @method('delete')
                  <a href="{{ route('visimisi.edit', $hasil->id ) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                  <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

@include('sweetalert::alert')







@endsection